version: '3'

services:
  mysql:
    image: mysql:5.7.23
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=sampleUser
      - MYSQL_PASSWORD=samplePass
      - MYSQL_DATABASE=sampleDb
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - "db-data:/var/lib/mysql"
  application:
    image: handson/tutorial3:latest
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=sampleUser
      - MYSQL_PASS=samplePass
      - MYSQL_DB=sampleDb
    depends_on:
      - mysql

volumes:
  db-data:
